name: flutter_here_maps
description: A new flutter plugin project.
version: 0.0.1+1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.etzuk.flutter.flutterheremaps
    pluginClass: FlutterHereMapsPlugin
