// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: map_objects.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum FlutterHereMaps_Animation: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case bow // = 0
  case linear // = 1
  case none // = 2
  case rocket // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .bow
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .bow
    case 1: self = .linear
    case 2: self = .none
    case 3: self = .rocket
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .bow: return 0
    case .linear: return 1
    case .none: return 2
    case .rocket: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension FlutterHereMaps_Animation: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [FlutterHereMaps_Animation] = [
    .bow,
    .linear,
    .none,
    .rocket,
  ]
}

#endif  // swift(>=4.2)

enum FlutterHereMaps_MapGestureEvents: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case onMultiFingerManipulationEnd // = 0
  case onPanEnd // = 1
  case onEventData // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .onMultiFingerManipulationEnd
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .onMultiFingerManipulationEnd
    case 1: self = .onPanEnd
    case 2: self = .onEventData
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .onMultiFingerManipulationEnd: return 0
    case .onPanEnd: return 1
    case .onEventData: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension FlutterHereMaps_MapGestureEvents: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [FlutterHereMaps_MapGestureEvents] = [
    .onMultiFingerManipulationEnd,
    .onPanEnd,
    .onEventData,
  ]
}

#endif  // swift(>=4.2)

struct FlutterHereMaps_Coordinate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var lat: Double = 0

  var lng: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FlutterHereMaps_Size {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var width: Float = 0

  var height: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FlutterHereMaps_ViewRect {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var x: Int32 = 0

  var y: Int32 = 0

  var width: Int32 = 0

  var height: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FlutterHereMaps_MapMarker {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var coordinate: FlutterHereMaps_Coordinate {
    get {return _storage._coordinate ?? FlutterHereMaps_Coordinate()}
    set {_uniqueStorage()._coordinate = newValue}
  }
  /// Returns true if `coordinate` has been explicitly set.
  var hasCoordinate: Bool {return _storage._coordinate != nil}
  /// Clears the value of `coordinate`. Subsequent reads from it will return its default value.
  mutating func clearCoordinate() {_uniqueStorage()._coordinate = nil}

  var size: FlutterHereMaps_Size {
    get {return _storage._size ?? FlutterHereMaps_Size()}
    set {_uniqueStorage()._size = newValue}
  }
  /// Returns true if `size` has been explicitly set.
  var hasSize: Bool {return _storage._size != nil}
  /// Clears the value of `size`. Subsequent reads from it will return its default value.
  mutating func clearSize() {_uniqueStorage()._size = nil}

  var image: String {
    get {return _storage._image}
    set {_uniqueStorage()._image = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_MapObject {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var uniqueID: String {
    get {return _storage._uniqueID}
    set {_uniqueStorage()._uniqueID = newValue}
  }

  var zIndex: Int32 {
    get {return _storage._zIndex}
    set {_uniqueStorage()._zIndex = newValue}
  }

  var visible: Bool {
    get {return _storage._visible}
    set {_uniqueStorage()._visible = newValue}
  }

  var object: OneOf_Object? {
    get {return _storage._object}
    set {_uniqueStorage()._object = newValue}
  }

  var marker: FlutterHereMaps_MapMarker {
    get {
      if case .marker(let v)? = _storage._object {return v}
      return FlutterHereMaps_MapMarker()
    }
    set {_uniqueStorage()._object = .marker(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Object: Equatable {
    case marker(FlutterHereMaps_MapMarker)

  #if !swift(>=4.1)
    static func ==(lhs: FlutterHereMaps_MapObject.OneOf_Object, rhs: FlutterHereMaps_MapObject.OneOf_Object) -> Bool {
      switch (lhs, rhs) {
      case (.marker(let l), .marker(let r)): return l == r
      }
    }
  #endif
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_MapCenter {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var coordinate: FlutterHereMaps_Coordinate {
    get {return _storage._coordinate ?? FlutterHereMaps_Coordinate()}
    set {_uniqueStorage()._coordinate = newValue}
  }
  /// Returns true if `coordinate` has been explicitly set.
  var hasCoordinate: Bool {return _storage._coordinate != nil}
  /// Clears the value of `coordinate`. Subsequent reads from it will return its default value.
  mutating func clearCoordinate() {_uniqueStorage()._coordinate = nil}

  var zoomLevel: FlutterHereMaps_FloatValue {
    get {return _storage._zoomLevel ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._zoomLevel = newValue}
  }
  /// Returns true if `zoomLevel` has been explicitly set.
  var hasZoomLevel: Bool {return _storage._zoomLevel != nil}
  /// Clears the value of `zoomLevel`. Subsequent reads from it will return its default value.
  mutating func clearZoomLevel() {_uniqueStorage()._zoomLevel = nil}

  var orientation: FlutterHereMaps_FloatValue {
    get {return _storage._orientation ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._orientation = newValue}
  }
  /// Returns true if `orientation` has been explicitly set.
  var hasOrientation: Bool {return _storage._orientation != nil}
  /// Clears the value of `orientation`. Subsequent reads from it will return its default value.
  mutating func clearOrientation() {_uniqueStorage()._orientation = nil}

  var tilt: FlutterHereMaps_FloatValue {
    get {return _storage._tilt ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._tilt = newValue}
  }
  /// Returns true if `tilt` has been explicitly set.
  var hasTilt: Bool {return _storage._tilt != nil}
  /// Clears the value of `tilt`. Subsequent reads from it will return its default value.
  mutating func clearTilt() {_uniqueStorage()._tilt = nil}

  var animation: FlutterHereMaps_Animation {
    get {return _storage._animation}
    set {_uniqueStorage()._animation = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_Configuration {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var trafficVisible: Bool {
    get {return _storage._trafficVisible}
    set {_uniqueStorage()._trafficVisible = newValue}
  }

  var positionIndicator: FlutterHereMaps_Configuration.PositionIndicator {
    get {return _storage._positionIndicator ?? FlutterHereMaps_Configuration.PositionIndicator()}
    set {_uniqueStorage()._positionIndicator = newValue}
  }
  /// Returns true if `positionIndicator` has been explicitly set.
  var hasPositionIndicator: Bool {return _storage._positionIndicator != nil}
  /// Clears the value of `positionIndicator`. Subsequent reads from it will return its default value.
  mutating func clearPositionIndicator() {_uniqueStorage()._positionIndicator = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct PositionIndicator {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var isVisible: FlutterHereMaps_BoolValue {
      get {return _storage._isVisible ?? FlutterHereMaps_BoolValue()}
      set {_uniqueStorage()._isVisible = newValue}
    }
    /// Returns true if `isVisible` has been explicitly set.
    var hasIsVisible: Bool {return _storage._isVisible != nil}
    /// Clears the value of `isVisible`. Subsequent reads from it will return its default value.
    mutating func clearIsVisible() {_uniqueStorage()._isVisible = nil}

    var isAccuracyIndicatorVisible: FlutterHereMaps_BoolValue {
      get {return _storage._isAccuracyIndicatorVisible ?? FlutterHereMaps_BoolValue()}
      set {_uniqueStorage()._isAccuracyIndicatorVisible = newValue}
    }
    /// Returns true if `isAccuracyIndicatorVisible` has been explicitly set.
    var hasIsAccuracyIndicatorVisible: Bool {return _storage._isAccuracyIndicatorVisible != nil}
    /// Clears the value of `isAccuracyIndicatorVisible`. Subsequent reads from it will return its default value.
    mutating func clearIsAccuracyIndicatorVisible() {_uniqueStorage()._isAccuracyIndicatorVisible = nil}

    var accuracyIndicatorColor: FlutterHereMaps_FloatValue {
      get {return _storage._accuracyIndicatorColor ?? FlutterHereMaps_FloatValue()}
      set {_uniqueStorage()._accuracyIndicatorColor = newValue}
    }
    /// Returns true if `accuracyIndicatorColor` has been explicitly set.
    var hasAccuracyIndicatorColor: Bool {return _storage._accuracyIndicatorColor != nil}
    /// Clears the value of `accuracyIndicatorColor`. Subsequent reads from it will return its default value.
    mutating func clearAccuracyIndicatorColor() {_uniqueStorage()._accuracyIndicatorColor = nil}

    var hue: FlutterHereMaps_FloatValue {
      get {return _storage._hue ?? FlutterHereMaps_FloatValue()}
      set {_uniqueStorage()._hue = newValue}
    }
    /// Returns true if `hue` has been explicitly set.
    var hasHue: Bool {return _storage._hue != nil}
    /// Clears the value of `hue`. Subsequent reads from it will return its default value.
    mutating func clearHue() {_uniqueStorage()._hue = nil}

    var orientationOffset: FlutterHereMaps_FloatValue {
      get {return _storage._orientationOffset ?? FlutterHereMaps_FloatValue()}
      set {_uniqueStorage()._orientationOffset = newValue}
    }
    /// Returns true if `orientationOffset` has been explicitly set.
    var hasOrientationOffset: Bool {return _storage._orientationOffset != nil}
    /// Clears the value of `orientationOffset`. Subsequent reads from it will return its default value.
    mutating func clearOrientationOffset() {_uniqueStorage()._orientationOffset = nil}

    var tracksCourse: FlutterHereMaps_BoolValue {
      get {return _storage._tracksCourse ?? FlutterHereMaps_BoolValue()}
      set {_uniqueStorage()._tracksCourse = newValue}
    }
    /// Returns true if `tracksCourse` has been explicitly set.
    var hasTracksCourse: Bool {return _storage._tracksCourse != nil}
    /// Clears the value of `tracksCourse`. Subsequent reads from it will return its default value.
    mutating func clearTracksCourse() {_uniqueStorage()._tracksCourse = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_ZoomTo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var coordinates: [FlutterHereMaps_Coordinate] {
    get {return _storage._coordinates}
    set {_uniqueStorage()._coordinates = newValue}
  }

  /// Optional
  var animation: FlutterHereMaps_Animation {
    get {return _storage._animation}
    set {_uniqueStorage()._animation = newValue}
  }

  /// Optional
  var orientation: FlutterHereMaps_FloatValue {
    get {return _storage._orientation ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._orientation = newValue}
  }
  /// Returns true if `orientation` has been explicitly set.
  var hasOrientation: Bool {return _storage._orientation != nil}
  /// Clears the value of `orientation`. Subsequent reads from it will return its default value.
  mutating func clearOrientation() {_uniqueStorage()._orientation = nil}

  /// Optional
  var perspective: FlutterHereMaps_FloatValue {
    get {return _storage._perspective ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._perspective = newValue}
  }
  /// Returns true if `perspective` has been explicitly set.
  var hasPerspective: Bool {return _storage._perspective != nil}
  /// Clears the value of `perspective`. Subsequent reads from it will return its default value.
  mutating func clearPerspective() {_uniqueStorage()._perspective = nil}

  /// Optional
  var viewRect: FlutterHereMaps_ViewRect {
    get {return _storage._viewRect ?? FlutterHereMaps_ViewRect()}
    set {_uniqueStorage()._viewRect = newValue}
  }
  /// Returns true if `viewRect` has been explicitly set.
  var hasViewRect: Bool {return _storage._viewRect != nil}
  /// Clears the value of `viewRect`. Subsequent reads from it will return its default value.
  mutating func clearViewRect() {_uniqueStorage()._viewRect = nil}

  /// Optional
  var paddingFactor: FlutterHereMaps_FloatValue {
    get {return _storage._paddingFactor ?? FlutterHereMaps_FloatValue()}
    set {_uniqueStorage()._paddingFactor = newValue}
  }
  /// Returns true if `paddingFactor` has been explicitly set.
  var hasPaddingFactor: Bool {return _storage._paddingFactor != nil}
  /// Clears the value of `paddingFactor`. Subsequent reads from it will return its default value.
  mutating func clearPaddingFactor() {_uniqueStorage()._paddingFactor = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_MapGesture {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var event: FlutterHereMaps_MapGestureEvents {
    get {return _storage._event}
    set {_uniqueStorage()._event = newValue}
  }

  var eventData: OneOf_EventData? {
    get {return _storage._eventData}
    set {_uniqueStorage()._eventData = newValue}
  }

  var longPressEvent: FlutterHereMaps_LongPressEvent {
    get {
      if case .longPressEvent(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_LongPressEvent()
    }
    set {_uniqueStorage()._eventData = .longPressEvent(newValue)}
  }

  var twoFingerTap: FlutterHereMaps_TwoFingerTap {
    get {
      if case .twoFingerTap(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_TwoFingerTap()
    }
    set {_uniqueStorage()._eventData = .twoFingerTap(newValue)}
  }

  var tiltEvent: FlutterHereMaps_TiltEvent {
    get {
      if case .tiltEvent(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_TiltEvent()
    }
    set {_uniqueStorage()._eventData = .tiltEvent(newValue)}
  }

  var doubleTap: FlutterHereMaps_DoubleTap {
    get {
      if case .doubleTap(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_DoubleTap()
    }
    set {_uniqueStorage()._eventData = .doubleTap(newValue)}
  }

  var tapEvent: FlutterHereMaps_TapEvent {
    get {
      if case .tapEvent(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_TapEvent()
    }
    set {_uniqueStorage()._eventData = .tapEvent(newValue)}
  }

  var pinchZoom: FlutterHereMaps_PinchZoom {
    get {
      if case .pinchZoom(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_PinchZoom()
    }
    set {_uniqueStorage()._eventData = .pinchZoom(newValue)}
  }

  var rotate: FlutterHereMaps_Rotate {
    get {
      if case .rotate(let v)? = _storage._eventData {return v}
      return FlutterHereMaps_Rotate()
    }
    set {_uniqueStorage()._eventData = .rotate(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_EventData: Equatable {
    case longPressEvent(FlutterHereMaps_LongPressEvent)
    case twoFingerTap(FlutterHereMaps_TwoFingerTap)
    case tiltEvent(FlutterHereMaps_TiltEvent)
    case doubleTap(FlutterHereMaps_DoubleTap)
    case tapEvent(FlutterHereMaps_TapEvent)
    case pinchZoom(FlutterHereMaps_PinchZoom)
    case rotate(FlutterHereMaps_Rotate)

  #if !swift(>=4.1)
    static func ==(lhs: FlutterHereMaps_MapGesture.OneOf_EventData, rhs: FlutterHereMaps_MapGesture.OneOf_EventData) -> Bool {
      switch (lhs, rhs) {
      case (.longPressEvent(let l), .longPressEvent(let r)): return l == r
      case (.twoFingerTap(let l), .twoFingerTap(let r)): return l == r
      case (.tiltEvent(let l), .tiltEvent(let r)): return l == r
      case (.doubleTap(let l), .doubleTap(let r)): return l == r
      case (.tapEvent(let l), .tapEvent(let r)): return l == r
      case (.pinchZoom(let l), .pinchZoom(let r)): return l == r
      case (.rotate(let l), .rotate(let r)): return l == r
      default: return false
      }
    }
  #endif
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_LongPressEvent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mapPoint: FlutterHereMaps_MapPoint {
    get {return _storage._mapPoint ?? FlutterHereMaps_MapPoint()}
    set {_uniqueStorage()._mapPoint = newValue}
  }
  /// Returns true if `mapPoint` has been explicitly set.
  var hasMapPoint: Bool {return _storage._mapPoint != nil}
  /// Clears the value of `mapPoint`. Subsequent reads from it will return its default value.
  mutating func clearMapPoint() {_uniqueStorage()._mapPoint = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_TwoFingerTap {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var point: FlutterHereMaps_MapPoint {
    get {return _storage._point ?? FlutterHereMaps_MapPoint()}
    set {_uniqueStorage()._point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  var hasPoint: Bool {return _storage._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  mutating func clearPoint() {_uniqueStorage()._point = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_DoubleTap {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var point: FlutterHereMaps_MapPoint {
    get {return _storage._point ?? FlutterHereMaps_MapPoint()}
    set {_uniqueStorage()._point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  var hasPoint: Bool {return _storage._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  mutating func clearPoint() {_uniqueStorage()._point = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_TiltEvent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tilt: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FlutterHereMaps_TapEvent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var point: FlutterHereMaps_MapPoint {
    get {return _storage._point ?? FlutterHereMaps_MapPoint()}
    set {_uniqueStorage()._point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  var hasPoint: Bool {return _storage._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  mutating func clearPoint() {_uniqueStorage()._point = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_PinchZoom {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var zoom: Float {
    get {return _storage._zoom}
    set {_uniqueStorage()._zoom = newValue}
  }

  var point: FlutterHereMaps_MapPoint {
    get {return _storage._point ?? FlutterHereMaps_MapPoint()}
    set {_uniqueStorage()._point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  var hasPoint: Bool {return _storage._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  mutating func clearPoint() {_uniqueStorage()._point = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_Rotate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rotate: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FlutterHereMaps_MapPoint {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var point: FlutterHereMaps_PointF {
    get {return _storage._point ?? FlutterHereMaps_PointF()}
    set {_uniqueStorage()._point = newValue}
  }
  /// Returns true if `point` has been explicitly set.
  var hasPoint: Bool {return _storage._point != nil}
  /// Clears the value of `point`. Subsequent reads from it will return its default value.
  mutating func clearPoint() {_uniqueStorage()._point = nil}

  var coordinate: FlutterHereMaps_Coordinate {
    get {return _storage._coordinate ?? FlutterHereMaps_Coordinate()}
    set {_uniqueStorage()._coordinate = newValue}
  }
  /// Returns true if `coordinate` has been explicitly set.
  var hasCoordinate: Bool {return _storage._coordinate != nil}
  /// Clears the value of `coordinate`. Subsequent reads from it will return its default value.
  mutating func clearCoordinate() {_uniqueStorage()._coordinate = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct FlutterHereMaps_PointF {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var x: Float = 0

  var y: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Wrapper message for `float`.
///
/// The JSON representation for `FloatValue` is JSON number.
struct FlutterHereMaps_FloatValue {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The float value.
  var value: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Wrapper message for `bool`.
///
/// The JSON representation for `BoolValue` is JSON `true` and `false`.
struct FlutterHereMaps_BoolValue {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The bool value.
  var value: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "FlutterHereMaps"

extension FlutterHereMaps_Animation: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Bow"),
    1: .same(proto: "Linear"),
    2: .same(proto: "None"),
    3: .same(proto: "Rocket"),
  ]
}

extension FlutterHereMaps_MapGestureEvents: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OnMultiFingerManipulationEnd"),
    1: .same(proto: "OnPanEnd"),
    2: .same(proto: "OnEventData"),
  ]
}

extension FlutterHereMaps_Coordinate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Coordinate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "lat"),
    2: .same(proto: "lng"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.lat)
      case 2: try decoder.decodeSingularDoubleField(value: &self.lng)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lat != 0 {
      try visitor.visitSingularDoubleField(value: self.lat, fieldNumber: 1)
    }
    if self.lng != 0 {
      try visitor.visitSingularDoubleField(value: self.lng, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_Coordinate, rhs: FlutterHereMaps_Coordinate) -> Bool {
    if lhs.lat != rhs.lat {return false}
    if lhs.lng != rhs.lng {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_Size: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Size"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "width"),
    2: .same(proto: "height"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.width)
      case 2: try decoder.decodeSingularFloatField(value: &self.height)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width != 0 {
      try visitor.visitSingularFloatField(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularFloatField(value: self.height, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_Size, rhs: FlutterHereMaps_Size) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_ViewRect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ViewRect"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
    3: .same(proto: "width"),
    4: .same(proto: "height"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.x)
      case 2: try decoder.decodeSingularInt32Field(value: &self.y)
      case 3: try decoder.decodeSingularInt32Field(value: &self.width)
      case 4: try decoder.decodeSingularInt32Field(value: &self.height)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x != 0 {
      try visitor.visitSingularInt32Field(value: self.x, fieldNumber: 1)
    }
    if self.y != 0 {
      try visitor.visitSingularInt32Field(value: self.y, fieldNumber: 2)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_ViewRect, rhs: FlutterHereMaps_ViewRect) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_MapMarker: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapMarker"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coordinate"),
    2: .same(proto: "size"),
    3: .same(proto: "image"),
  ]

  fileprivate class _StorageClass {
    var _coordinate: FlutterHereMaps_Coordinate? = nil
    var _size: FlutterHereMaps_Size? = nil
    var _image: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _coordinate = source._coordinate
      _size = source._size
      _image = source._image
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._coordinate)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._size)
        case 3: try decoder.decodeSingularStringField(value: &_storage._image)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._coordinate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._size {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if !_storage._image.isEmpty {
        try visitor.visitSingularStringField(value: _storage._image, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_MapMarker, rhs: FlutterHereMaps_MapMarker) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._coordinate != rhs_storage._coordinate {return false}
        if _storage._size != rhs_storage._size {return false}
        if _storage._image != rhs_storage._image {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_MapObject: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapObject"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "uniqueId"),
    2: .same(proto: "zIndex"),
    3: .same(proto: "visible"),
    4: .same(proto: "marker"),
  ]

  fileprivate class _StorageClass {
    var _uniqueID: String = String()
    var _zIndex: Int32 = 0
    var _visible: Bool = false
    var _object: FlutterHereMaps_MapObject.OneOf_Object?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uniqueID = source._uniqueID
      _zIndex = source._zIndex
      _visible = source._visible
      _object = source._object
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._uniqueID)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._zIndex)
        case 3: try decoder.decodeSingularBoolField(value: &_storage._visible)
        case 4:
          var v: FlutterHereMaps_MapMarker?
          if let current = _storage._object {
            try decoder.handleConflictingOneOf()
            if case .marker(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._object = .marker(v)}
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._uniqueID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uniqueID, fieldNumber: 1)
      }
      if _storage._zIndex != 0 {
        try visitor.visitSingularInt32Field(value: _storage._zIndex, fieldNumber: 2)
      }
      if _storage._visible != false {
        try visitor.visitSingularBoolField(value: _storage._visible, fieldNumber: 3)
      }
      if case .marker(let v)? = _storage._object {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_MapObject, rhs: FlutterHereMaps_MapObject) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uniqueID != rhs_storage._uniqueID {return false}
        if _storage._zIndex != rhs_storage._zIndex {return false}
        if _storage._visible != rhs_storage._visible {return false}
        if _storage._object != rhs_storage._object {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_MapCenter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapCenter"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Coordinate"),
    2: .same(proto: "zoomLevel"),
    3: .same(proto: "orientation"),
    4: .same(proto: "tilt"),
    5: .same(proto: "animation"),
  ]

  fileprivate class _StorageClass {
    var _coordinate: FlutterHereMaps_Coordinate? = nil
    var _zoomLevel: FlutterHereMaps_FloatValue? = nil
    var _orientation: FlutterHereMaps_FloatValue? = nil
    var _tilt: FlutterHereMaps_FloatValue? = nil
    var _animation: FlutterHereMaps_Animation = .bow

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _coordinate = source._coordinate
      _zoomLevel = source._zoomLevel
      _orientation = source._orientation
      _tilt = source._tilt
      _animation = source._animation
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._coordinate)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._zoomLevel)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._orientation)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._tilt)
        case 5: try decoder.decodeSingularEnumField(value: &_storage._animation)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._coordinate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._zoomLevel {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._orientation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._tilt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if _storage._animation != .bow {
        try visitor.visitSingularEnumField(value: _storage._animation, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_MapCenter, rhs: FlutterHereMaps_MapCenter) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._coordinate != rhs_storage._coordinate {return false}
        if _storage._zoomLevel != rhs_storage._zoomLevel {return false}
        if _storage._orientation != rhs_storage._orientation {return false}
        if _storage._tilt != rhs_storage._tilt {return false}
        if _storage._animation != rhs_storage._animation {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_Configuration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Configuration"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "trafficVisible"),
    2: .same(proto: "positionIndicator"),
  ]

  fileprivate class _StorageClass {
    var _trafficVisible: Bool = false
    var _positionIndicator: FlutterHereMaps_Configuration.PositionIndicator? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _trafficVisible = source._trafficVisible
      _positionIndicator = source._positionIndicator
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularBoolField(value: &_storage._trafficVisible)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._positionIndicator)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._trafficVisible != false {
        try visitor.visitSingularBoolField(value: _storage._trafficVisible, fieldNumber: 1)
      }
      if let v = _storage._positionIndicator {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_Configuration, rhs: FlutterHereMaps_Configuration) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._trafficVisible != rhs_storage._trafficVisible {return false}
        if _storage._positionIndicator != rhs_storage._positionIndicator {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_Configuration.PositionIndicator: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = FlutterHereMaps_Configuration.protoMessageName + ".PositionIndicator"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "isVisible"),
    2: .same(proto: "isAccuracyIndicatorVisible"),
    3: .same(proto: "accuracyIndicatorColor"),
    4: .same(proto: "hue"),
    5: .same(proto: "orientationOffset"),
    6: .same(proto: "tracksCourse"),
  ]

  fileprivate class _StorageClass {
    var _isVisible: FlutterHereMaps_BoolValue? = nil
    var _isAccuracyIndicatorVisible: FlutterHereMaps_BoolValue? = nil
    var _accuracyIndicatorColor: FlutterHereMaps_FloatValue? = nil
    var _hue: FlutterHereMaps_FloatValue? = nil
    var _orientationOffset: FlutterHereMaps_FloatValue? = nil
    var _tracksCourse: FlutterHereMaps_BoolValue? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _isVisible = source._isVisible
      _isAccuracyIndicatorVisible = source._isAccuracyIndicatorVisible
      _accuracyIndicatorColor = source._accuracyIndicatorColor
      _hue = source._hue
      _orientationOffset = source._orientationOffset
      _tracksCourse = source._tracksCourse
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._isVisible)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._isAccuracyIndicatorVisible)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._accuracyIndicatorColor)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._hue)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._orientationOffset)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._tracksCourse)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._isVisible {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._isAccuracyIndicatorVisible {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._accuracyIndicatorColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._hue {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._orientationOffset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._tracksCourse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_Configuration.PositionIndicator, rhs: FlutterHereMaps_Configuration.PositionIndicator) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._isVisible != rhs_storage._isVisible {return false}
        if _storage._isAccuracyIndicatorVisible != rhs_storage._isAccuracyIndicatorVisible {return false}
        if _storage._accuracyIndicatorColor != rhs_storage._accuracyIndicatorColor {return false}
        if _storage._hue != rhs_storage._hue {return false}
        if _storage._orientationOffset != rhs_storage._orientationOffset {return false}
        if _storage._tracksCourse != rhs_storage._tracksCourse {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_ZoomTo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ZoomTo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coordinates"),
    2: .same(proto: "animation"),
    3: .same(proto: "orientation"),
    4: .same(proto: "perspective"),
    5: .same(proto: "viewRect"),
    6: .same(proto: "paddingFactor"),
  ]

  fileprivate class _StorageClass {
    var _coordinates: [FlutterHereMaps_Coordinate] = []
    var _animation: FlutterHereMaps_Animation = .bow
    var _orientation: FlutterHereMaps_FloatValue? = nil
    var _perspective: FlutterHereMaps_FloatValue? = nil
    var _viewRect: FlutterHereMaps_ViewRect? = nil
    var _paddingFactor: FlutterHereMaps_FloatValue? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _coordinates = source._coordinates
      _animation = source._animation
      _orientation = source._orientation
      _perspective = source._perspective
      _viewRect = source._viewRect
      _paddingFactor = source._paddingFactor
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeRepeatedMessageField(value: &_storage._coordinates)
        case 2: try decoder.decodeSingularEnumField(value: &_storage._animation)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._orientation)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._perspective)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._viewRect)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._paddingFactor)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._coordinates.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._coordinates, fieldNumber: 1)
      }
      if _storage._animation != .bow {
        try visitor.visitSingularEnumField(value: _storage._animation, fieldNumber: 2)
      }
      if let v = _storage._orientation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._perspective {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._viewRect {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._paddingFactor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_ZoomTo, rhs: FlutterHereMaps_ZoomTo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._coordinates != rhs_storage._coordinates {return false}
        if _storage._animation != rhs_storage._animation {return false}
        if _storage._orientation != rhs_storage._orientation {return false}
        if _storage._perspective != rhs_storage._perspective {return false}
        if _storage._viewRect != rhs_storage._viewRect {return false}
        if _storage._paddingFactor != rhs_storage._paddingFactor {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_MapGesture: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapGesture"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "event"),
    100: .same(proto: "longPressEvent"),
    101: .same(proto: "twoFingerTap"),
    102: .same(proto: "tiltEvent"),
    103: .same(proto: "doubleTap"),
    104: .same(proto: "tapEvent"),
    105: .same(proto: "pinchZoom"),
    106: .same(proto: "rotate"),
  ]

  fileprivate class _StorageClass {
    var _event: FlutterHereMaps_MapGestureEvents = .onMultiFingerManipulationEnd
    var _eventData: FlutterHereMaps_MapGesture.OneOf_EventData?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _event = source._event
      _eventData = source._eventData
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularEnumField(value: &_storage._event)
        case 100:
          var v: FlutterHereMaps_LongPressEvent?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .longPressEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .longPressEvent(v)}
        case 101:
          var v: FlutterHereMaps_TwoFingerTap?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .twoFingerTap(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .twoFingerTap(v)}
        case 102:
          var v: FlutterHereMaps_TiltEvent?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .tiltEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .tiltEvent(v)}
        case 103:
          var v: FlutterHereMaps_DoubleTap?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .doubleTap(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .doubleTap(v)}
        case 104:
          var v: FlutterHereMaps_TapEvent?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .tapEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .tapEvent(v)}
        case 105:
          var v: FlutterHereMaps_PinchZoom?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .pinchZoom(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .pinchZoom(v)}
        case 106:
          var v: FlutterHereMaps_Rotate?
          if let current = _storage._eventData {
            try decoder.handleConflictingOneOf()
            if case .rotate(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._eventData = .rotate(v)}
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._event != .onMultiFingerManipulationEnd {
        try visitor.visitSingularEnumField(value: _storage._event, fieldNumber: 1)
      }
      switch _storage._eventData {
      case .longPressEvent(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      case .twoFingerTap(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
      case .tiltEvent(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
      case .doubleTap(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
      case .tapEvent(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
      case .pinchZoom(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 105)
      case .rotate(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 106)
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_MapGesture, rhs: FlutterHereMaps_MapGesture) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._event != rhs_storage._event {return false}
        if _storage._eventData != rhs_storage._eventData {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_LongPressEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LongPressEvent"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "map_point"),
  ]

  fileprivate class _StorageClass {
    var _mapPoint: FlutterHereMaps_MapPoint? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _mapPoint = source._mapPoint
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._mapPoint)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._mapPoint {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_LongPressEvent, rhs: FlutterHereMaps_LongPressEvent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._mapPoint != rhs_storage._mapPoint {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_TwoFingerTap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TwoFingerTap"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "point"),
  ]

  fileprivate class _StorageClass {
    var _point: FlutterHereMaps_MapPoint? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _point = source._point
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._point)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._point {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_TwoFingerTap, rhs: FlutterHereMaps_TwoFingerTap) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._point != rhs_storage._point {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_DoubleTap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DoubleTap"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "point"),
  ]

  fileprivate class _StorageClass {
    var _point: FlutterHereMaps_MapPoint? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _point = source._point
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._point)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._point {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_DoubleTap, rhs: FlutterHereMaps_DoubleTap) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._point != rhs_storage._point {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_TiltEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TiltEvent"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "tilt"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.tilt)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tilt != 0 {
      try visitor.visitSingularFloatField(value: self.tilt, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_TiltEvent, rhs: FlutterHereMaps_TiltEvent) -> Bool {
    if lhs.tilt != rhs.tilt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_TapEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TapEvent"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "point"),
  ]

  fileprivate class _StorageClass {
    var _point: FlutterHereMaps_MapPoint? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _point = source._point
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._point)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._point {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_TapEvent, rhs: FlutterHereMaps_TapEvent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._point != rhs_storage._point {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_PinchZoom: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PinchZoom"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "zoom"),
    2: .same(proto: "point"),
  ]

  fileprivate class _StorageClass {
    var _zoom: Float = 0
    var _point: FlutterHereMaps_MapPoint? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _zoom = source._zoom
      _point = source._point
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularFloatField(value: &_storage._zoom)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._point)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._zoom != 0 {
        try visitor.visitSingularFloatField(value: _storage._zoom, fieldNumber: 1)
      }
      if let v = _storage._point {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_PinchZoom, rhs: FlutterHereMaps_PinchZoom) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._zoom != rhs_storage._zoom {return false}
        if _storage._point != rhs_storage._point {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_Rotate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Rotate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "rotate"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.rotate)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rotate != 0 {
      try visitor.visitSingularFloatField(value: self.rotate, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_Rotate, rhs: FlutterHereMaps_Rotate) -> Bool {
    if lhs.rotate != rhs.rotate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_MapPoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapPoint"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "point"),
    2: .same(proto: "coordinate"),
  ]

  fileprivate class _StorageClass {
    var _point: FlutterHereMaps_PointF? = nil
    var _coordinate: FlutterHereMaps_Coordinate? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _point = source._point
      _coordinate = source._coordinate
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._point)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._coordinate)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._point {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._coordinate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_MapPoint, rhs: FlutterHereMaps_MapPoint) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._point != rhs_storage._point {return false}
        if _storage._coordinate != rhs_storage._coordinate {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_PointF: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PointF"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.x)
      case 2: try decoder.decodeSingularFloatField(value: &self.y)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_PointF, rhs: FlutterHereMaps_PointF) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_FloatValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FloatValue"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularFloatField(value: &self.value)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != 0 {
      try visitor.visitSingularFloatField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_FloatValue, rhs: FlutterHereMaps_FloatValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlutterHereMaps_BoolValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoolValue"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.value)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != false {
      try visitor.visitSingularBoolField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FlutterHereMaps_BoolValue, rhs: FlutterHereMaps_BoolValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
